name: Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java-version: ["11"]
                llvm-version: ["12.0.1"]
                node-version: ["16.14.0"]
                wasmtime-version: ["0.21.0"]
                wabt-version: ["1.0.27"]

        steps:

        - uses: actions/checkout@v2

        - name: Use Java ${{ matrix.java-version }}
          uses: actions/setup-java@v1
          with:
              java-version: ${{ matrix.java-version }}

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}

        - name: Use LLVM ${{ matrix.llvm-version }}
          uses: KyleMayes/install-llvm-action@v1
          with:
              version: ${{ matrix.llvm-version }}
              directory: ${{ runner.temp }}/llvm

        - name: Use wasmtime ${{ matrix.wasmtime-version }}
          uses: mwilliamson/setup-wasmtime-action@v1
          with:
              wasmtime-version: ${{ matrix.wasmtime-version }}

        - name: Use wabt ${{ matrix.wabt-version }}
          uses: mwilliamson/setup-wabt-action@v1
          with:
              wabt-version: ${{ matrix.wabt-version }}

        - run: make test
